### ISSUE TITLE
Grey blank screen

### ISSUE THREAD

**Issue by tutlewst1** [Romanysoft/CSSDesigner#1]
I just bought this app for my mac and it just puts up a grey blank screen.

**Comment by lauer3912** [comment]
@tutlewst1 Can you provide a screenshot and your mac version?

**Comment by lauer3912** [comment]
@tutlewst1 

Thank you very much for your feedback!
We have fixed the problem, has offered version 4.1. After approval, after the update, you will be able to normal use.
