### ISSUE TITLE
Just a grey screen here too

### ISSUE THREAD

**Issue by clanli** [Romanysoft/CSSDesigner#2]
Hi

I just bought CSSDesigner and I just get a grey blank screen with no controllers at all.
I am attaching a screenshot.
Mac OS X  Systemversion:
OS X 10.11.3 (15D21)
Kärnversion:   Darwin 15.3.0
![skarmavbild 2016-03-02 kl 19 47 52](https://cloud.githubusercontent.com/assets/17600287/13471541/48a1a920-e0b1-11e5-98bb-395b6f8094e3.png)

**Comment by lauer3912** [comment]
@clanli 

Thank you very much for your feedback!
We have fixed the problem, has offered version 4.1. After approval, after the update, you will be able to normal use.

**Comment by clanli** [comment]
Thanks!
