### ISSUE TITLE
Some controllers are missing?

### ISSUE THREAD

**Issue by clanli** [Romanysoft/CSSDesigner#3]
Hi guys!

I think some controllers are missing. I have no idea how to create a second layer and when I look at the pictures on Apple Store I can se a "+" and "-" sign, and some more. But I can't se any on my screen.
I am running: OS X 10.11.3 (15D21), with CSS Design version 4.1 (201603062100). Se attached file. 

![screen shot 2016-03-18 at 20 52 49](https://cloud.githubusercontent.com/assets/17600287/13890632/cb6abe3a-ed4c-11e5-8855-fc814c83c94f.png)

**Comment by lauer3912** [comment]
Hi, clanli

Thanks for your feedback.
We have found the product to release on the App Store, as indeed as you describe. Today we released a modified version. Please wait for the upgrade.

Thanks again.
